name: hk_db

on:
  push:
    branches:
      - main
    paths:
      - .github/**
  schedule:
    # At 10:30 every day
    - cron: "30 10 * * 6"

jobs:
  hk:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          repository: wtydavid99/covid19_cases
    
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.6"

      - name: Check Version
        id: check-version
        run: |
          [[ "$(poetry version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] \
            || echo ::set-output name=prerelease::true

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-dev

      - name: Collect data
        run: |
          poetry run python -m covid19_cases.hk_database \

          
